<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TownsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $towns = [

            //الخليل
            ['city_id' => 1, 'town_name' => 'مخيم الفوار'],
            ['city_id' => 1, 'town_name' => 'مخيم العروب'],
            ['city_id' => 1, 'town_name' => 'يطا'],
            ['city_id' => 1, 'town_name' => 'قنان جابر'],
            ['city_id' => 1, 'town_name' => 'زيف'],
            ['city_id' => 1, 'town_name' => 'وادي الشاجنة'],
            ['city_id' => 1, 'town_name' => 'طرامة'],
            ['city_id' => 1, 'town_name' => 'دير رازح'],
            ['city_id' => 1, 'town_name' => 'نوبا'],
            ['city_id' => 1, 'town_name' => 'مغاير العبيد'],
            ['city_id' => 1, 'town_name' => 'قواويس'],
            ['city_id' => 1, 'town_name' => 'طوبا'],
            ['city_id' => 1, 'town_name' => 'شعيب البطم'],
            ['city_id' => 1, 'town_name' => 'سدة الثعلة'],
            ['city_id' => 1, 'town_name' => 'خربة بير العد'],
            ['city_id' => 1, 'town_name' => 'خربة الفخيت'],
            ['city_id' => 1, 'town_name' => 'خربة اصفي (الفوقا والتحتا)'],
            ['city_id' => 1, 'town_name' => 'المقعورة'],
            ['city_id' => 1, 'town_name' => 'كرمة'],
            ['city_id' => 1, 'town_name' => 'كرزة'],
            ['city_id' => 1, 'town_name' => 'صوريف'],
            ['city_id' => 1, 'town_name' => 'شيوخ العروب'],
            ['city_id' => 1, 'town_name' => 'سوسيا'],
            ['city_id' => 1, 'town_name' => 'طواس'],
            ['city_id' => 1, 'town_name' => 'سكة'],
            ['city_id' => 1, 'town_name' => 'وادي الريم'],
            ['city_id' => 1, 'town_name' => 'كوازيبا'],
            ['city_id' => 1, 'town_name' => 'قنان النمر'],
            ['city_id' => 1, 'town_name' => 'سعير'],
            ['city_id' => 1, 'town_name' => 'حمروش'],
            ['city_id' => 1, 'town_name' => 'بيت عينون'],
            ['city_id' => 1, 'town_name' => 'أم البطم'],
            ['city_id' => 1, 'town_name' => 'أبو العرقان'],
            ['city_id' => 1, 'town_name' => 'رابود'],
            ['city_id' => 1, 'town_name' => 'طاروسة'],
            ['city_id' => 1, 'town_name' => 'دير سامت'],
            ['city_id' => 1, 'town_name' => 'دير العسل الفوقا'],
            ['city_id' => 1, 'town_name' => 'دير العسل التحتا'],
            ['city_id' => 1, 'town_name' => 'إسكيك'],
            ['city_id' => 1, 'town_name' => 'وادي عبيد'],
            ['city_id' => 1, 'town_name' => 'دورا'],
            ['city_id' => 1, 'town_name' => 'خلة المية'],
            ['city_id' => 1, 'town_name' => 'أم لصفا وأبو شبان'],
            ['city_id' => 1, 'town_name' => 'أم العمد (سهل واد الماء)'],
            ['city_id' => 1, 'town_name' => 'أم الشقحان'],
            ['city_id' => 1, 'town_name' => 'الرفاعية والديرات'],
            ['city_id' => 1, 'town_name' => 'البويب'],
            ['city_id' => 1, 'town_name' => 'خشم الكرم'],
            ['city_id' => 1, 'town_name' => 'خشم الدرج (الهذالين)'],
            ['city_id' => 1, 'town_name' => 'خرسا'],
            ['city_id' => 1, 'town_name' => 'خربة زنوتة'],
            ['city_id' => 1, 'town_name' => 'خربة أم الخير'],
            ['city_id' => 1, 'town_name' => 'خربة الدير'],
            ['city_id' => 1, 'town_name' => 'خاراس'],
            ['city_id' => 1, 'town_name' => 'حلحول'],
            ['city_id' => 1, 'town_name' => 'حدب الفوار'],
            ['city_id' => 1, 'town_name' => 'حتى'],
            ['city_id' => 1, 'town_name' => 'تفوح'],
            ['city_id' => 1, 'town_name' => 'خربة جمروة'],
            ['city_id' => 1, 'town_name' => 'ترقوميا'],
            ['city_id' => 1, 'town_name' => 'بيرين'],
            ['city_id' => 1, 'town_name' => 'بيت كاحل'],
            ['city_id' => 1, 'town_name' => 'بيت عوا'],
            ['city_id' => 1, 'town_name' => 'بيت عمرة'],
            ['city_id' => 1, 'town_name' => 'بيت أولا'],
            ['city_id' => 1, 'town_name' => 'جالا'],
            ['city_id' => 1, 'town_name' => 'بيت أمر'],
            ['city_id' => 1, 'town_name' => 'بيت الروش الفوقا'],
            ['city_id' => 1, 'town_name' => 'بيت الروش التحتا'],
            ['city_id' => 1, 'town_name' => 'مسافر بني نعيم (خلة المسافر)'],
            ['city_id' => 1, 'town_name' => 'بني نعيم'],
            ['city_id' => 1, 'town_name' => 'العين'],
            ['city_id' => 1, 'town_name' => 'هريبة النبي'],
            ['city_id' => 1, 'town_name' => 'إمنيزيل'],
            ['city_id' => 1, 'town_name' => 'إمريش'],
            ['city_id' => 1, 'town_name' => 'أم الخير'],
            ['city_id' => 1, 'town_name' => 'النجادة'],
            ['city_id' => 1, 'town_name' => 'المجد'],
            ['city_id' => 1, 'town_name' => 'حمصة'],
            ['city_id' => 1, 'town_name' => 'بيت مقدوم'],
            ['city_id' => 1, 'town_name' => 'المورق'],
            ['city_id' => 1, 'town_name' => 'الكوم'],
            ['city_id' => 1, 'town_name' => 'الكعابنة - أم الدرج (الزويدين)'],
            ['city_id' => 1, 'town_name' => 'الكرمل'],
            ['city_id' => 1, 'town_name' => 'عناب الكبير'],
            ['city_id' => 1, 'town_name' => 'كفر جول'],
            ['city_id' => 1, 'town_name' => 'سومرة'],
            ['city_id' => 1, 'town_name' => 'خربة شويكة'],
            ['city_id' => 1, 'town_name' => 'خربة دير شمس'],
            ['city_id' => 1, 'town_name' => 'الظاهرية'],
            ['city_id' => 1, 'town_name' => 'إقطيط'],
            ['city_id' => 1, 'town_name' => 'أبو الحنا'],
            ['city_id' => 1, 'town_name' => 'وادي الكلاب'],
            ['city_id' => 1, 'town_name' => 'مراح البقار'],
            ['city_id' => 1, 'town_name' => 'الصرة'],
            ['city_id' => 1, 'town_name' => 'الشيوخ'],
            ['city_id' => 1, 'town_name' => 'مجد الباع'],
            ['city_id' => 1, 'town_name' => 'خربة غوين الفوقا'],
            ['city_id' => 1, 'town_name' => 'خربة الرظيم'],
            ['city_id' => 1, 'town_name' => 'خربة الخرابة'],
            ['city_id' => 1, 'town_name' => 'السموع'],
            ['city_id' => 1, 'town_name' => 'الريحية'],
            ['city_id' => 1, 'town_name' => 'عرب الفريجات'],
            ['city_id' => 1, 'town_name' => 'خربة الرهوة'],
            ['city_id' => 1, 'town_name' => 'الرماضين'],
            ['city_id' => 1, 'town_name' => 'قلقس'],
            ['city_id' => 1, 'town_name' => 'قلاع زيتا'],
            ['city_id' => 1, 'town_name' => 'خلة الدار'],
            ['city_id' => 1, 'town_name' => 'الخليل'],
            ['city_id' => 1, 'town_name' => 'البويرة (عقبة انجيلة)'],
            ['city_id' => 1, 'town_name' => 'البويرة (البقعة)'],
            ['city_id' => 1, 'town_name' => 'خربة صارورة'],
            ['city_id' => 1, 'town_name' => 'المفقرة'],
            ['city_id' => 1, 'town_name' => 'الركيز'],
            ['city_id' => 1, 'town_name' => 'التواني'],
            ['city_id' => 1, 'town_name' => 'بيت مرسم'],
            ['city_id' => 1, 'town_name' => 'البرج والبيرة'],
            ['city_id' => 1, 'town_name' => 'سوبا'],
            ['city_id' => 1, 'town_name' => 'إذنا'],
            ['city_id' => 1, 'town_name' => 'إدقيقة (خربة طويل الشيح)'],
            ['city_id' => 1, 'town_name' => 'أبو الغزلان'],
            ['city_id' => 1, 'town_name' => 'أبو العسجا'],

            //اريحا والاغوار
            ['city_id' => 6, 'town_name' => 'مخيم عين السلطان'],
            ['city_id' => 6, 'town_name' => 'مخيم عقبة جبر'],
            ['city_id' => 6, 'town_name' => 'مرج نعجة'],
            ['city_id' => 6, 'town_name' => 'مرج الغزال'],
            ['city_id' => 6, 'town_name' => 'فصايل'],
            ['city_id' => 6, 'town_name' => 'عين الديوك الفوقا'],
            ['city_id' => 6, 'town_name' => 'النويعمة'],
            ['city_id' => 6, 'town_name' => 'العوجا'],
            ['city_id' => 6, 'town_name' => 'الزبيدات'],
            ['city_id' => 6, 'town_name' => 'الجفتلك'],
            ['city_id' => 6, 'town_name' => 'دير حجلة'],
            ['city_id' => 6, 'town_name' => 'دير القلط'],
            ['city_id' => 6, 'town_name' => 'النبي موسى'],
            ['city_id' => 6, 'town_name' => 'أريحا'],

            //القدس
            ['city_id' => 9, 'town_name' => 'مخيم قلنديا'],
            ['city_id' => 9, 'town_name' => 'وادي الجوز'],
            ['city_id' => 9, 'town_name' => 'مخيم شعفاط'],
            ['city_id' => 9, 'town_name' => 'صور باهر'],
            ['city_id' => 9, 'town_name' => 'شيخ جراح'],
            ['city_id' => 9, 'town_name' => 'شعفاط'],
            ['city_id' => 9, 'town_name' => 'شرفات'],
            ['city_id' => 9, 'town_name' => 'سلوان'],
            ['city_id' => 9, 'town_name' => 'راس العامود'],
            ['city_id' => 9, 'town_name' => 'جبل المكبّر'],
            ['city_id' => 9, 'town_name' => 'بيت صفافا'],
            ['city_id' => 9, 'town_name' => 'بيت حنينا'],
            ['city_id' => 9, 'town_name' => 'باب الساهرة'],
            ['city_id' => 9, 'town_name' => 'أم طوبا'],
            ['city_id' => 9, 'town_name' => 'القدس (بيت المقدس)'],
            ['city_id' => 9, 'town_name' => 'العيسوية'],
            ['city_id' => 9, 'town_name' => 'الطور (جبل الزيتون)'],
            ['city_id' => 9, 'town_name' => 'الصوانة'],
            ['city_id' => 9, 'town_name' => 'الشياح'],
            ['city_id' => 9, 'town_name' => 'السواحرة الغربية'],
            ['city_id' => 9, 'town_name' => 'الثوري'],
            ['city_id' => 9, 'town_name' => 'مخماس'],
            ['city_id' => 9, 'town_name' => 'كفر عقب'],
            ['city_id' => 9, 'town_name' => 'قلنديا'],
            ['city_id' => 9, 'town_name' => 'قطنة'],
            ['city_id' => 9, 'town_name' => 'عناتا'],
            ['city_id' => 9, 'town_name' => 'عرب الجهالين (سلامات)'],
            ['city_id' => 9, 'town_name' => 'رافات'],
            ['city_id' => 9, 'town_name' => 'خرائب أم اللحم'],
            ['city_id' => 9, 'town_name' => 'حزما'],
            ['city_id' => 9, 'town_name' => 'جبع'],
            ['city_id' => 9, 'town_name' => 'بير نبالا'],
            ['city_id' => 9, 'town_name' => 'بيت عنان'],
            ['city_id' => 9, 'town_name' => 'بيت سوريك'],
            ['city_id' => 9, 'town_name' => 'بيت دقو'],
            ['city_id' => 9, 'town_name' => 'بيت حنينا البلد'],
            ['city_id' => 9, 'town_name' => 'بيت إكسا'],
            ['city_id' => 9, 'town_name' => 'بيت إجزا'],
            ['city_id' => 9, 'town_name' => 'بدو'],
            ['city_id' => 9, 'town_name' => 'النبي صموئيل'],
            ['city_id' => 9, 'town_name' => 'القبية'],
            ['city_id' => 9, 'town_name' => 'الكعابنة (تجمع بدوي)'],
            ['city_id' => 9, 'town_name' => 'العيزرية'],
            ['city_id' => 9, 'town_name' => 'الشيخ سعد'],
            ['city_id' => 9, 'town_name' => 'السواحرة الشرقية'],
            ['city_id' => 9, 'town_name' => 'الزعيم'],
            ['city_id' => 9, 'town_name' => 'الرام وضاحية البريد'],
            ['city_id' => 9, 'town_name' => 'الخان الأحمر'],
            ['city_id' => 9, 'town_name' => 'الجيب'],
            ['city_id' => 9, 'town_name' => 'الجديرة'],
            ['city_id' => 9, 'town_name' => 'أبو ديس'],

            //بيت لحم
            ['city_id' => 15, 'town_name' => 'مخيم عايدة'],
            ['city_id' => 15, 'town_name' => 'مخيم العزة'],
            ['city_id' => 15, 'town_name' => 'مخيم الدهيشة'],
            ['city_id' => 15, 'town_name' => 'وادي فوكين'],
            ['city_id' => 15, 'town_name' => 'وادي رحال'],
            ['city_id' => 15, 'town_name' => 'وادي النيص'],
            ['city_id' => 15, 'town_name' => 'هندازة وبريضعة'],
            ['city_id' => 15, 'town_name' => 'خلة اللوزة'],
            ['city_id' => 15, 'town_name' => 'نحالين'],
            ['city_id' => 15, 'town_name' => 'مراح معلا'],
            ['city_id' => 15, 'town_name' => 'مراح رباح'],
            ['city_id' => 15, 'town_name' => 'كيسان'],
            ['city_id' => 15, 'town_name' => 'عرب الرشايدة'],
            ['city_id' => 15, 'town_name' => 'زعترة'],
            ['city_id' => 15, 'town_name' => 'راس الواد'],
            ['city_id' => 15, 'town_name' => 'دار صلاح'],
            ['city_id' => 15, 'town_name' => 'خلة عفانة'],
            ['city_id' => 15, 'town_name' => 'خلة سكاريا'],
            ['city_id' => 15, 'town_name' => 'خلة البلوطة'],
            ['city_id' => 15, 'town_name' => 'خلة النعمان'],
            ['city_id' => 15, 'town_name' => 'خلة الحداد'],
            ['city_id' => 15, 'town_name' => 'حوسان'],
            ['city_id' => 15, 'town_name' => 'جورة الشمعة'],
            ['city_id' => 15, 'town_name' => 'جناتا (بد فلوح)'],
            ['city_id' => 15, 'town_name' => 'خربة تقوع'],
            ['city_id' => 15, 'town_name' => 'خربة الدير'],
            ['city_id' => 15, 'town_name' => 'تقوع'],
            ['city_id' => 15, 'town_name' => 'الحلقوم'],
            ['city_id' => 15, 'town_name' => 'بيت لحم'],
            ['city_id' => 15, 'town_name' => 'بيت فجار'],
            ['city_id' => 15, 'town_name' => 'بيت ساحور'],
            ['city_id' => 15, 'town_name' => 'خلة حمامة'],
            ['city_id' => 15, 'town_name' => 'بيت جالا'],
            ['city_id' => 15, 'town_name' => 'بئر عونة'],
            ['city_id' => 15, 'town_name' => 'جب الذيب'],
            ['city_id' => 15, 'town_name' => 'بيت تعمر'],
            ['city_id' => 15, 'town_name' => 'الفريديس'],
            ['city_id' => 15, 'town_name' => 'بتير'],
            ['city_id' => 15, 'town_name' => 'أم سلمونة'],
            ['city_id' => 15, 'town_name' => 'إرطاس'],
            ['city_id' => 15, 'town_name' => 'الولجة'],
            ['city_id' => 15, 'town_name' => 'وادي أمحيميد'],
            ['city_id' => 15, 'town_name' => 'المنيا'],
            ['city_id' => 15, 'town_name' => 'المنشية'],
            ['city_id' => 15, 'town_name' => 'المعصرة'],
            ['city_id' => 15, 'town_name' => 'العبيدية'],
            ['city_id' => 15, 'town_name' => 'الحدادية'],
            ['city_id' => 15, 'town_name' => 'الشواورة'],
            ['city_id' => 15, 'town_name' => 'الدوحة'],
            ['city_id' => 15, 'town_name' => 'الخضر'],
            ['city_id' => 15, 'town_name' => 'الخاص'],
            ['city_id' => 15, 'town_name' => 'الجبعة'],

            //جنين
            ['city_id' => 8, 'town_name' => 'الجديدة'],
            ['city_id' => 8, 'town_name' => 'الجلمة'],
            ['city_id' => 8, 'town_name' => 'الحفيرة (حفيرة عرابة)'],
            ['city_id' => 8, 'town_name' => 'الضمايرة'],
            ['city_id' => 8, 'town_name' => 'الخلجان'],
            ['city_id' => 8, 'town_name' => 'الرامة'],
            ['city_id' => 8, 'town_name' => 'الزاوية'],
            ['city_id' => 8, 'town_name' => 'الزبابدة'],
            ['city_id' => 8, 'town_name' => 'الشهداء (مثلث الشهداء)'],
            ['city_id' => 8, 'town_name' => 'الطيبة'],
            ['city_id' => 8, 'town_name' => 'العرقة'],
            ['city_id' => 8, 'town_name' => 'العصاعصة'],
            ['city_id' => 8, 'town_name' => 'العطارة'],
            ['city_id' => 8, 'town_name' => 'الفندقومية'],
            ['city_id' => 8, 'town_name' => 'الكفير'],
            ['city_id' => 8, 'town_name' => 'المطلة'],
            ['city_id' => 8, 'town_name' => 'المغير'],
            ['city_id' => 8, 'town_name' => 'المنصورة'],
            ['city_id' => 8, 'town_name' => 'الهاشمية'],
            ['city_id' => 8, 'town_name' => 'اليامون'],
            ['city_id' => 8, 'town_name' => 'خربة سروج'],
            ['city_id' => 8, 'town_name' => 'أم التوت'],
            ['city_id' => 8, 'town_name' => 'أم الريحان'],
            ['city_id' => 8, 'town_name' => 'أم دار'],
            ['city_id' => 8, 'town_name' => 'برطعة الشرقية'],
            ['city_id' => 8, 'town_name' => 'برقين'],
            ['city_id' => 8, 'town_name' => 'بيت قاد (الجنوبي)'],
            ['city_id' => 8, 'town_name' => 'بير الباشا'],
            ['city_id' => 8, 'town_name' => 'تعنك'],
            ['city_id' => 8, 'town_name' => 'تلفيت'],
            ['city_id' => 8, 'town_name' => 'تنين'],
            ['city_id' => 8, 'town_name' => 'جبع'],
            ['city_id' => 8, 'town_name' => 'جلبون'],
            ['city_id' => 8, 'town_name' => 'جلقموس'],
            ['city_id' => 8, 'town_name' => 'جنين'],
            ['city_id' => 8, 'town_name' => 'عابا (الغربية)'],
            ['city_id' => 8, 'town_name' => 'خربة عبد الله اليونس'],
            ['city_id' => 8, 'town_name' => 'الجميلات'],
            ['city_id' => 8, 'town_name' => 'دير أبو ضعيف'],
            ['city_id' => 8, 'town_name' => 'دير غزالة'],
            ['city_id' => 8, 'town_name' => 'رابا'],
            ['city_id' => 8, 'town_name' => 'رمانة'],
            ['city_id' => 8, 'town_name' => 'خربة المنطار الشرقية'],
            ['city_id' => 8, 'town_name' => 'خربة المنطار الغربية'],
            ['city_id' => 8, 'town_name' => 'زبدة'],
            ['city_id' => 8, 'town_name' => 'زبوبا'],
            ['city_id' => 8, 'town_name' => 'سيريس'],
            ['city_id' => 8, 'town_name' => 'السعايدة'],
            ['city_id' => 8, 'town_name' => 'سيلة الحارثية'],
            ['city_id' => 8, 'town_name' => 'سيلة الظهر'],
            ['city_id' => 8, 'town_name' => 'الجربا'],
            ['city_id' => 8, 'town_name' => 'صانور'],
            ['city_id' => 8, 'town_name' => 'صير'],
            ['city_id' => 8, 'town_name' => 'طورة الشرقية'],
            ['city_id' => 8, 'town_name' => 'طورة الغربية'],
            ['city_id' => 8, 'town_name' => 'ظهر العبد'],
            ['city_id' => 8, 'town_name' => 'ظهر المالح'],
            ['city_id' => 8, 'town_name' => 'عانين'],
            ['city_id' => 8, 'town_name' => 'عجة'],
            ['city_id' => 8, 'town_name' => 'عرابة'],
            ['city_id' => 8, 'town_name' => 'عرانة'],
            ['city_id' => 8, 'town_name' => 'عربونة'],
            ['city_id' => 8, 'town_name' => 'فحمة'],
            ['city_id' => 8, 'town_name' => 'فحمة الجديدة'],
            ['city_id' => 8, 'town_name' => 'فراسين'],
            ['city_id' => 8, 'town_name' => 'فقوعة'],
            ['city_id' => 8, 'town_name' => 'قباطية'],
            ['city_id' => 8, 'town_name' => 'كفر دان'],
            ['city_id' => 8, 'town_name' => 'كفر راعي'],
            ['city_id' => 8, 'town_name' => 'كفر قود'],
            ['city_id' => 8, 'town_name' => 'كفيرت'],
            ['city_id' => 8, 'town_name' => 'مركة'],
            ['city_id' => 8, 'town_name' => 'مسيلية'],
            ['city_id' => 8, 'town_name' => 'مشروع بيت قاد (الشمالي)'],
            ['city_id' => 8, 'town_name' => 'ميثالون'],
            ['city_id' => 8, 'town_name' => 'نزلة الشيخ زيد'],
            ['city_id' => 8, 'town_name' => 'وادي الضبع (عابا الشرقية)'],
            ['city_id' => 8, 'town_name' => 'وادي دعوق'],
            ['city_id' => 8, 'town_name' => 'الطرم'],
            ['city_id' => 8, 'town_name' => 'إمريحة'],
            ['city_id' => 8, 'town_name' => 'خربة الحمام'],
            ['city_id' => 8, 'town_name' => 'يعبد'],
            ['city_id' => 8, 'town_name' => 'مخيم جنين'],

            //خانيونس
            ['city_id' => 12, 'town_name' => 'عبسان الكبيرة'],
            ['city_id' => 12, 'town_name' => 'عبسان الجديدة'],
            ['city_id' => 12, 'town_name' => 'خزاعة'],
            ['city_id' => 12, 'town_name' => 'مخيم خانيونس'],
            ['city_id' => 12, 'town_name' => 'خانيونس'],
            ['city_id' => 12, 'town_name' => 'بني سهيلا'],
            ['city_id' => 12, 'town_name' => 'القرارة'],
            ['city_id' => 12, 'town_name' => 'الفخاري'],

            //دير البلح
            ['city_id' => 17, 'town_name' => 'وادي السلقا'],
            ['city_id' => 17, 'town_name' => 'مخيم دير البلح'],
            ['city_id' => 17, 'town_name' => 'دير البلح'],
            ['city_id' => 17, 'town_name' => 'مخيم النصيرات'],
            ['city_id' => 17, 'town_name' => 'النصيرات'],
            ['city_id' => 17, 'town_name' => 'مخيم المغازي'],
            ['city_id' => 17, 'town_name' => 'المغازي'],
            ['city_id' => 17, 'town_name' => 'المصدر'],
            ['city_id' => 17, 'town_name' => 'الزوايدة'],
            ['city_id' => 17, 'town_name' => 'مخيم البريج'],
            ['city_id' => 17, 'town_name' => 'البريج'],


            //رام الله والبيرة
            ['city_id' => 4, 'town_name' => 'مخيم قدورة'],
            ['city_id' => 4, 'town_name' => 'مخيم دير عمار'],
            ['city_id' => 4, 'town_name' => 'مخيم الجلزون'],
            ['city_id' => 4, 'town_name' => 'مخيم الأمعري'],
            ['city_id' => 4, 'town_name' => 'يالو'],
            ['city_id' => 4, 'town_name' => 'عمواس'],
            ['city_id' => 4, 'town_name' => 'بيت نوبا'],
            ['city_id' => 4, 'town_name' => 'يبرود'],
            ['city_id' => 4, 'town_name' => 'نعلين'],
            ['city_id' => 4, 'town_name' => 'مزارع النوباني'],
            ['city_id' => 4, 'town_name' => 'كوبر'],
            ['city_id' => 4, 'town_name' => 'كفر نعمة'],
            ['city_id' => 4, 'town_name' => 'كفر مالك'],
            ['city_id' => 4, 'town_name' => 'كفر عين'],
            ['city_id' => 4, 'town_name' => 'قراوة بني زيد'],
            ['city_id' => 4, 'town_name' => 'قبيا'],
            ['city_id' => 4, 'town_name' => 'عين يبرود'],
            ['city_id' => 4, 'town_name' => 'عين قينيا'],
            ['city_id' => 4, 'town_name' => 'عين عريك'],
            ['city_id' => 4, 'town_name' => 'عطارة'],
            ['city_id' => 4, 'town_name' => 'عجول'],
            ['city_id' => 4, 'town_name' => 'عبوين'],
            ['city_id' => 4, 'town_name' => 'عارورة'],
            ['city_id' => 4, 'town_name' => 'عابود'],
            ['city_id' => 4, 'town_name' => 'صفا'],
            ['city_id' => 4, 'town_name' => 'صردا'],
            ['city_id' => 4, 'town_name' => 'أبو قش'],
            ['city_id' => 4, 'town_name' => 'شقبا'],
            ['city_id' => 4, 'town_name' => 'شبتين'],
            ['city_id' => 4, 'town_name' => 'سنجل'],
            ['city_id' => 4, 'town_name' => 'مخيم سلواد'],
            ['city_id' => 4, 'town_name' => 'سلواد'],
            ['city_id' => 4, 'town_name' => 'روابي'],
            ['city_id' => 4, 'town_name' => 'رنتيس'],
            ['city_id' => 4, 'town_name' => 'رمون'],
            ['city_id' => 4, 'town_name' => 'رام الله'],
            ['city_id' => 4, 'town_name' => 'رأس كركر'],
            ['city_id' => 4, 'town_name' => 'دير نظام'],
            ['city_id' => 4, 'town_name' => 'دير قديس'],
            ['city_id' => 4, 'town_name' => 'دير عمار'],
            ['city_id' => 4, 'town_name' => 'دير دبوان'],
            ['city_id' => 4, 'town_name' => 'دير جرير'],
            ['city_id' => 4, 'town_name' => 'دير السودان'],
            ['city_id' => 4, 'town_name' => 'دير أبو مشعل'],
            ['city_id' => 4, 'town_name' => 'دير إبزيع'],
            ['city_id' => 4, 'town_name' => 'دورا القرع'],
            ['city_id' => 4, 'town_name' => 'خربثا بني حارث'],
            ['city_id' => 4, 'town_name' => 'خربثا المصباح'],
            ['city_id' => 4, 'town_name' => 'خربة أبو فلاح'],
            ['city_id' => 4, 'town_name' => 'جيبيا'],
            ['city_id' => 4, 'town_name' => 'جمالا'],
            ['city_id' => 4, 'town_name' => 'جلجيلية'],
            ['city_id' => 4, 'town_name' => 'جفنا'],
            ['city_id' => 4, 'town_name' => 'الدوحة'],
            ['city_id' => 4, 'town_name' => 'ترمسعيا'],
            ['city_id' => 4, 'town_name' => 'بيرزيت'],
            ['city_id' => 4, 'town_name' => 'بيتين'],
            ['city_id' => 4, 'town_name' => 'بيتونيا'],
            ['city_id' => 4, 'town_name' => 'بيت لقيا'],
            ['city_id' => 4, 'town_name' => 'بيت عور الفوقا'],
            ['city_id' => 4, 'town_name' => 'بيت عور التحتا'],
            ['city_id' => 4, 'town_name' => 'بيت سيرا'],
            ['city_id' => 4, 'town_name' => 'دير غسانة'],
            ['city_id' => 4, 'town_name' => 'بيت ريما'],
            ['city_id' => 4, 'town_name' => 'بلعين'],
            ['city_id' => 4, 'town_name' => 'برهام'],
            ['city_id' => 4, 'town_name' => 'برقة'],
            ['city_id' => 4, 'town_name' => 'بدرس'],
            ['city_id' => 4, 'town_name' => 'أم صفا'],
            ['city_id' => 4, 'town_name' => 'النبي صالح'],
            ['city_id' => 4, 'town_name' => 'المغير'],
            ['city_id' => 4, 'town_name' => 'المزرعة القبلية'],
            ['city_id' => 4, 'town_name' => 'المزرعة الشرقية'],
            ['city_id' => 4, 'town_name' => 'المدية'],
            ['city_id' => 4, 'town_name' => 'اللبن الغربي'],
            ['city_id' => 4, 'town_name' => 'الطيرة'],
            ['city_id' => 4, 'town_name' => 'بدو المعرجات'],
            ['city_id' => 4, 'town_name' => 'الطيبة'],
            ['city_id' => 4, 'town_name' => 'الجانية'],
            ['city_id' => 4, 'town_name' => 'البيرة'],
            ['city_id' => 4, 'town_name' => 'أبو شخيدم'],

            //رفح
            ['city_id' => 13, 'town_name' => 'مخيم رفح'],
            ['city_id' => 13, 'town_name' => 'رفح'],
            ['city_id' => 13, 'town_name' => 'النصر'],
            ['city_id' => 13, 'town_name' => 'الشوكة'],

            //سلفيت
            ['city_id' => 16, 'town_name' => 'ياسوف'],
            ['city_id' => 16, 'town_name' => 'مسحة'],
            ['city_id' => 16, 'town_name' => 'مردا'],
            ['city_id' => 16, 'town_name' => 'كفل حارس'],
            ['city_id' => 16, 'town_name' => 'كفر الديك'],
            ['city_id' => 16, 'town_name' => 'قيرة'],
            ['city_id' => 16, 'town_name' => 'قراوة بني حسان'],
            ['city_id' => 16, 'town_name' => 'فرخة'],
            ['city_id' => 16, 'town_name' => 'سلفيت'],
            ['city_id' => 16, 'town_name' => 'خربة قيس'],
            ['city_id' => 16, 'town_name' => 'عزبة أبو آدم'],
            ['city_id' => 16, 'town_name' => 'سرطة'],
            ['city_id' => 16, 'town_name' => 'رافات'],
            ['city_id' => 16, 'town_name' => 'دير بلوط'],
            ['city_id' => 16, 'town_name' => 'دير استيا'],
            ['city_id' => 16, 'town_name' => 'حارس'],
            ['city_id' => 16, 'town_name' => 'بروقين'],
            ['city_id' => 16, 'town_name' => 'بديا'],
            ['city_id' => 16, 'town_name' => 'الزاوية'],
            ['city_id' => 16, 'town_name' => 'إسكاكا'],

            //شمال غزة
            ['city_id' => 18, 'town_name' => 'مخيم جباليا'],
            ['city_id' => 18, 'town_name' => 'جباليا'],
            ['city_id' => 18, 'town_name' => 'بيت لاهيا'],
            ['city_id' => 18, 'town_name' => 'بيت حانون'],
            ['city_id' => 18, 'town_name' => 'أم النصر (القرية البدوية)'],

            //طوباس
            ['city_id' => 14, 'town_name' => 'مخيم الفارعة'],

            //طوباس والأغوار الشمالية
            ['city_id' => 19, 'town_name' => 'وادي الفارعة'],
            ['city_id' => 19, 'town_name' => 'كردلة'],
            ['city_id' => 19, 'town_name' => 'عين البيضا'],
            ['city_id' => 19, 'town_name' => 'عقابا'],
            ['city_id' => 19, 'town_name' => 'كشدة'],
            ['city_id' => 19, 'town_name' => 'طوباس'],
            ['city_id' => 19, 'town_name' => 'سلحب'],
            ['city_id' => 19, 'town_name' => 'طمون'],
            ['city_id' => 19, 'town_name' => 'راس الفارعة'],
            ['city_id' => 19, 'town_name' => 'خربة يرزة'],
            ['city_id' => 19, 'town_name' => 'خربة عاطوف'],
            ['city_id' => 19, 'town_name' => 'خربة الراس الأحمر'],
            ['city_id' => 19, 'town_name' => 'تياسير'],
            ['city_id' => 19, 'town_name' => 'بردلة'],
            ['city_id' => 19, 'town_name' => 'عين الحلوة'],
            ['city_id' => 19, 'town_name' => 'خربة تل الحمة'],
            ['city_id' => 19, 'town_name' => 'المالح'],
            ['city_id' => 19, 'town_name' => 'الفارسية'],
            ['city_id' => 19, 'town_name' => 'الحديدية'],
            ['city_id' => 19, 'town_name' => 'العقبة'],
            ['city_id' => 19, 'town_name' => 'إبزيق'],

            //طولكرم
            ['city_id' => 2, 'town_name' => 'مخيم نور شمس'],
            ['city_id' => 2, 'town_name' => 'مخيم طولكرم'],
            ['city_id' => 2, 'town_name' => 'نزلة عيسى'],
            ['city_id' => 2, 'town_name' => 'كور'],
            ['city_id' => 2, 'town_name' => 'كفر عبوش'],
            ['city_id' => 2, 'town_name' => 'كفر صور'],
            ['city_id' => 2, 'town_name' => 'كفر زيباد'],
            ['city_id' => 2, 'town_name' => 'كفر جمال'],
            ['city_id' => 2, 'town_name' => 'كفر اللبد'],
            ['city_id' => 2, 'town_name' => 'عزبة الخلال'],
            ['city_id' => 2, 'town_name' => 'عزبة أبو خميش'],
            ['city_id' => 2, 'town_name' => 'الحفاصي'],
            ['city_id' => 2, 'town_name' => 'قفين'],
            ['city_id' => 2, 'town_name' => 'فرعون'],
            ['city_id' => 2, 'town_name' => 'عنبتا'],
            ['city_id' => 2, 'town_name' => 'علاّر'],
            ['city_id' => 2, 'town_name' => 'عكابة'],
            ['city_id' => 2, 'town_name' => 'عتيل'],
            ['city_id' => 2, 'town_name' => 'كفا'],
            ['city_id' => 2, 'town_name' => 'طولكرم'],
            ['city_id' => 2, 'town_name' => 'شويكة'],
            ['city_id' => 2, 'town_name' => 'ذنابة'],
            ['city_id' => 2, 'town_name' => 'خربة الطياح'],
            ['city_id' => 2, 'town_name' => 'ارتاح'],
            ['city_id' => 2, 'town_name' => 'صيدا'],
            ['city_id' => 2, 'town_name' => 'عزبة شوفة'],
            ['city_id' => 2, 'town_name' => 'شوفة'],
            ['city_id' => 2, 'town_name' => 'سفارين'],
            ['city_id' => 2, 'town_name' => 'زيتا'],
            ['city_id' => 2, 'town_name' => 'رامين'],
            ['city_id' => 2, 'town_name' => 'دير الغصون'],
            ['city_id' => 2, 'town_name' => 'المسقوفة'],
            ['city_id' => 2, 'town_name' => 'خربة جبارة'],
            ['city_id' => 2, 'town_name' => 'بيت ليد'],
            ['city_id' => 2, 'town_name' => 'بلعا'],
            ['city_id' => 2, 'town_name' => 'باقة الشرقية'],
            ['city_id' => 2, 'town_name' => 'النزلة الوسطى'],
            ['city_id' => 2, 'town_name' => 'النزلة الغربية'],
            ['city_id' => 2, 'town_name' => 'النزلة الشرقية'],
            ['city_id' => 2, 'town_name' => 'الراس'],
            ['city_id' => 2, 'town_name' => 'الجاروشية'],
            ['city_id' => 2, 'town_name' => 'إكتابا'],

            //غزة
            ['city_id' => 7, 'town_name' => 'مدينة الزهراء'],
            ['city_id' => 7, 'town_name' => 'مخيم الشاطىء'],
            ['city_id' => 7, 'town_name' => 'غزة'],
            ['city_id' => 7, 'town_name' => 'جحر الديك'],
            ['city_id' => 7, 'town_name' => 'المغراقه'],

            //قلقيلية
            ['city_id' => 5, 'town_name' => 'كفر لاقف'],
            ['city_id' => 5, 'town_name' => 'كفر قدّوم'],
            ['city_id' => 5, 'town_name' => 'كفر ثلث'],
            ['city_id' => 5, 'town_name' => 'عرب الخوله'],
            ['city_id' => 5, 'town_name' => 'قلقيلية'],
            ['city_id' => 5, 'town_name' => 'فلامية'],
            ['city_id' => 5, 'town_name' => 'فرعتا'],
            ['city_id' => 5, 'town_name' => 'عسلة'],
            ['city_id' => 5, 'town_name' => 'عزون عتمة'],
            ['city_id' => 5, 'town_name' => 'عزون'],
            ['city_id' => 5, 'town_name' => 'عزبة الطبيب'],
            ['city_id' => 5, 'town_name' => 'عرب الرماضين الشمالي'],
            ['city_id' => 5, 'town_name' => 'عرب الرماضين الجنوبي'],
            ['city_id' => 5, 'town_name' => 'عرب أبو فردة'],
            ['city_id' => 5, 'town_name' => 'سنيريا'],
            ['city_id' => 5, 'town_name' => 'وادي الرشا'],
            ['city_id' => 5, 'town_name' => 'راس عطية'],
            ['city_id' => 5, 'town_name' => 'راس الطيرة'],
            ['city_id' => 5, 'town_name' => 'خربة صير'],
            ['city_id' => 5, 'town_name' => 'حجة'],
            ['city_id' => 5, 'town_name' => 'حبلة'],
            ['city_id' => 5, 'town_name' => 'جيوس'],
            ['city_id' => 5, 'town_name' => 'جيت'],
            ['city_id' => 5, 'town_name' => 'جنصافوط'],
            ['city_id' => 5, 'town_name' => 'بيت أمين'],
            ['city_id' => 5, 'town_name' => 'باقة الحطب'],
            ['city_id' => 5, 'town_name' => 'إمّاتين'],
            ['city_id' => 5, 'town_name' => 'النبي إلياس'],
            ['city_id' => 5, 'town_name' => 'الفندق'],
            ['city_id' => 5, 'town_name' => 'عزبة سلمان'],
            ['city_id' => 5, 'town_name' => 'عزبة جلعود'],
            ['city_id' => 5, 'town_name' => 'عزبة الأشقر'],
            ['city_id' => 5, 'town_name' => 'المدور'],
            ['city_id' => 5, 'town_name' => 'الضبعة'],

            //نابلس
            ['city_id' => 10, 'town_name' => 'مخيم عين بيت الماء'],
            ['city_id' => 10, 'town_name' => 'مخيم عسكر (الجديد)'],
            ['city_id' => 10, 'town_name' => 'مخيم عسكر (القديم)'],
            ['city_id' => 10, 'town_name' => 'مخيم بلاطة'],
            ['city_id' => 10, 'town_name' => 'يتما'],
            ['city_id' => 10, 'town_name' => 'ياصيد'],
            ['city_id' => 10, 'town_name' => 'نصف جبيل'],
            ['city_id' => 10, 'town_name' => 'نابلس'],
            ['city_id' => 10, 'town_name' => 'مجدل بني فاضل'],
            ['city_id' => 10, 'town_name' => 'مادما'],
            ['city_id' => 10, 'town_name' => 'كفر قليل'],
            ['city_id' => 10, 'town_name' => 'قوصين'],
            ['city_id' => 10, 'town_name' => 'قصرة'],
            ['city_id' => 10, 'town_name' => 'قريوت'],
            ['city_id' => 10, 'town_name' => 'خربة صرة'],
            ['city_id' => 10, 'town_name' => 'قبلان'],
            ['city_id' => 10, 'town_name' => 'فروش بيت دجن'],
            ['city_id' => 10, 'town_name' => 'عينبوس'],
            ['city_id' => 10, 'town_name' => 'عين شبلي'],
            ['city_id' => 10, 'town_name' => 'عوريف'],
            ['city_id' => 10, 'town_name' => 'عوارتا'],
            ['city_id' => 10, 'town_name' => 'عمورية'],
            ['city_id' => 10, 'town_name' => 'يانون'],
            ['city_id' => 10, 'town_name' => 'عقربا'],
            ['city_id' => 10, 'town_name' => 'الطويل وتل الخشبة'],
            ['city_id' => 10, 'town_name' => 'الرجمان والدوا'],
            ['city_id' => 10, 'town_name' => 'عصيرة القبلية'],
            ['city_id' => 10, 'town_name' => 'عصيرة الشمالية'],
            ['city_id' => 10, 'town_name' => 'عزموط'],
            ['city_id' => 10, 'town_name' => 'عراق بورين'],
            ['city_id' => 10, 'town_name' => 'طلوزة'],
            ['city_id' => 10, 'town_name' => 'صرة'],
            ['city_id' => 10, 'town_name' => 'سبسطية'],
            ['city_id' => 10, 'town_name' => 'سالم'],
            ['city_id' => 10, 'town_name' => 'زيتا جماعين'],
            ['city_id' => 10, 'town_name' => 'زواتا'],
            ['city_id' => 10, 'town_name' => 'روجيب'],
            ['city_id' => 10, 'town_name' => 'دير شرف'],
            ['city_id' => 10, 'town_name' => 'دير الحطب'],
            ['city_id' => 10, 'town_name' => 'دوما'],
            ['city_id' => 10, 'town_name' => 'حوارة'],
            ['city_id' => 10, 'town_name' => 'جوريش'],
            ['city_id' => 10, 'town_name' => 'جماعين'],
            ['city_id' => 10, 'town_name' => 'جالود'],
            ['city_id' => 10, 'town_name' => 'تلفيت'],
            ['city_id' => 10, 'town_name' => 'تل'],
            ['city_id' => 10, 'town_name' => 'زعترة'],
            ['city_id' => 10, 'town_name' => 'بيتا'],
            ['city_id' => 10, 'town_name' => 'بيت وزن'],
            ['city_id' => 10, 'town_name' => 'خربة طانا'],
            ['city_id' => 10, 'town_name' => 'بيت فوريك'],
            ['city_id' => 10, 'town_name' => 'بيت دجن'],
            ['city_id' => 10, 'town_name' => 'بيت حسن'],
            ['city_id' => 10, 'town_name' => 'بيت إيبا'],
            ['city_id' => 10, 'town_name' => 'بيت إمرين'],
            ['city_id' => 10, 'town_name' => 'بورين'],
            ['city_id' => 10, 'town_name' => 'بزارية'],
            ['city_id' => 10, 'town_name' => 'برقة'],
            ['city_id' => 10, 'town_name' => 'أوصرين'],
            ['city_id' => 10, 'town_name' => 'أودلا'],
            ['city_id' => 10, 'town_name' => 'إجنسينا'],
            ['city_id' => 10, 'town_name' => 'النصارية'],
            ['city_id' => 10, 'town_name' => 'الناقورة'],
            ['city_id' => 10, 'town_name' => 'أللبن الشرقية'],
            ['city_id' => 10, 'town_name' => 'العقربانية'],
            ['city_id' => 10, 'town_name' => 'الساوية'],
            ['city_id' => 10, 'town_name' => 'الباذان'],
        ];

        DB::table('towns')->insert($towns);
    }
}
