<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TownsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $towns = [

            //الخليل
            ['city_id' => 1, 'town_name' => 'البرج'],
            ['city_id' => 1, 'town_name' => 'البقعة'],
            ['city_id' => 1, 'town_name' => 'البويب'],
            ['city_id' => 1, 'town_name' => 'البويره (عقبة انجيله)'],
            ['city_id' => 1, 'town_name' => 'التواني'],
            ['city_id' => 1, 'town_name' => 'الحيلة'],
            ['city_id' => 1, 'town_name' => 'الخليل'],
            ['city_id' => 1, 'town_name' => 'الديرات'],
            ['city_id' => 1, 'town_name' => 'الرماضين'],
            ['city_id' => 1, 'town_name' => 'الريحية'],
            ['city_id' => 1, 'town_name' => 'السموع'],
            ['city_id' => 1, 'town_name' => 'الشيوخ'],
            ['city_id' => 1, 'town_name' => 'الصرة'],
            ['city_id' => 1, 'town_name' => 'الظاهرية'],
            ['city_id' => 1, 'town_name' => 'الكرمل'],
            ['city_id' => 1, 'town_name' => 'المجد'],
            ['city_id' => 1, 'town_name' => 'النجادة'],
            ['city_id' => 1, 'town_name' => 'أم الخير'],
            ['city_id' => 1, 'town_name' => 'إذنا'],
            ['city_id' => 1, 'town_name' => 'إمريش'],
            ['city_id' => 1, 'town_name' => 'إمنيزل'],
            ['city_id' => 1, 'town_name' => 'أم الدرج (عرب الكعابنه)'],
            ['city_id' => 1, 'town_name' => 'أم الشقحان'],
            ['city_id' => 1, 'town_name' => 'أم الصفا'],
            ['city_id' => 1, 'town_name' => 'أم العمد (سهل واد الماء)'],
            ['city_id' => 1, 'town_name' => 'بني نعيم'],
            ['city_id' => 1, 'town_name' => 'بيت الروش التحتا'],
            ['city_id' => 1, 'town_name' => 'بيت الروش الفوقا'],
            ['city_id' => 1, 'town_name' => 'بيت أولا'],
            ['city_id' => 1, 'town_name' => 'بيت أومر'],
            ['city_id' => 1, 'town_name' => 'بيت عمرة'],
            ['city_id' => 1, 'town_name' => 'بيت عوا'],
            ['city_id' => 1, 'town_name' => 'بيت عينون'],
            ['city_id' => 1, 'town_name' => 'بيت كاحل'],
            ['city_id' => 1, 'town_name' => 'بيت مرسم'],
            ['city_id' => 1, 'town_name' => 'بيت مقدوم'],
            ['city_id' => 1, 'town_name' => 'ترقوميا'],
            ['city_id' => 1, 'town_name' => 'تفوح'],
            ['city_id' => 1, 'town_name' => 'جالا'],
            ['city_id' => 1, 'town_name' => 'حتا'],
            ['city_id' => 1, 'town_name' => 'حدب العلقة'],
            ['city_id' => 1, 'town_name' => 'حدب ألفوار'],
            ['city_id' => 1, 'town_name' => 'حلحول'],
            ['city_id' => 1, 'town_name' => 'خاراس'],
            ['city_id' => 1, 'town_name' => 'خربة الدير'],
            ['city_id' => 1, 'town_name' => 'خربة الفخيت'],
            ['city_id' => 1, 'town_name' => 'خربة سلامة'],
            ['city_id' => 1, 'town_name' => 'خربة طويل الشيح'],
            ['city_id' => 1, 'town_name' => 'خرسا'],
            ['city_id' => 1, 'town_name' => 'خشم الدرج (الهذالين)'],
            ['city_id' => 1, 'town_name' => 'خلة  الدار'],
            ['city_id' => 1, 'town_name' => 'خلة العقد'],
            ['city_id' => 1, 'town_name' => 'خلة المسافر'],
            ['city_id' => 1, 'town_name' => 'خلة المية'],
            ['city_id' => 1, 'town_name' => 'خلة صالح'],
            ['city_id' => 1, 'town_name' => 'خيروشيوش والحديدية'],
            ['city_id' => 1, 'town_name' => 'دورا'],
            ['city_id' => 1, 'town_name' => 'دير العسل التحتا'],
            ['city_id' => 1, 'town_name' => 'دير العسل الفوقا'],
            ['city_id' => 1, 'town_name' => 'دير رازح'],
            ['city_id' => 1, 'town_name' => 'دير سامت'],
            ['city_id' => 1, 'town_name' => 'رابود'],
            ['city_id' => 1, 'town_name' => 'زيف'],
            ['city_id' => 1, 'town_name' => 'سعير'],
            ['city_id' => 1, 'town_name' => 'سكة'],
            ['city_id' => 1, 'town_name' => 'شيوخ العروب'],
            ['city_id' => 1, 'town_name' => 'صوريف'],
            ['city_id' => 1, 'town_name' => 'طرامة'],
            ['city_id' => 1, 'town_name' => 'عرب الفريجات'],
            ['city_id' => 1, 'town_name' => 'عناب الكبير'],
            ['city_id' => 1, 'town_name' => 'فقيقيس'],
            ['city_id' => 1, 'town_name' => 'قلاع زيتا'],
            ['city_id' => 1, 'town_name' => 'قلقس'],
            ['city_id' => 1, 'town_name' => 'كرزة'],
            ['city_id' => 1, 'town_name' => 'كرمة'],
            ['city_id' => 1, 'town_name' => 'مخيم العروب'],
            ['city_id' => 1, 'town_name' => 'مخيم الفوار'],
            ['city_id' => 1, 'town_name' => 'مراح البقار'],
            ['city_id' => 1, 'town_name' => 'معين'],
            ['city_id' => 1, 'town_name' => 'منطقة شعب البطن'],
            ['city_id' => 1, 'town_name' => 'نوبا'],
            ['city_id' => 1, 'town_name' => 'وادي الشاجنة'],
            ['city_id' => 1, 'town_name' => 'وادي العماير'],
            ['city_id' => 1, 'town_name' => 'وادي عبيد'],
            ['city_id' => 1, 'town_name' => 'يطا'],

            //نابلس
            ['city_id' => 10, 'town_name' => 'الباذان'],
            ['city_id' => 10, 'town_name' => 'الساوية'],
            ['city_id' => 10, 'town_name' => 'العقربانية'],
            ['city_id' => 10, 'town_name' => 'اللبن الشرقية'],
            ['city_id' => 10, 'town_name' => 'الناقورة'],
            ['city_id' => 10, 'town_name' => 'النصارية'],
            ['city_id' => 10, 'town_name' => 'إجنسنيا'],
            ['city_id' => 10, 'town_name' => 'أودلا'],
            ['city_id' => 10, 'town_name' => 'أوصرين'],
            ['city_id' => 10, 'town_name' => 'برقة'],
            ['city_id' => 10, 'town_name' => 'بزاريا'],
            ['city_id' => 10, 'town_name' => 'بورين'],
            ['city_id' => 10, 'town_name' => 'بيت إمرين'],
            ['city_id' => 10, 'town_name' => 'بيت إيبا'],
            ['city_id' => 10, 'town_name' => 'بيت حسن'],
            ['city_id' => 10, 'town_name' => 'بيت دجن'],
            ['city_id' => 10, 'town_name' => 'بيت فوريك'],
            ['city_id' => 10, 'town_name' => 'بيت وزن'],
            ['city_id' => 10, 'town_name' => 'بيتا'],
            ['city_id' => 10, 'town_name' => 'تل'],
            ['city_id' => 10, 'town_name' => 'تلفيت'],
            ['city_id' => 10, 'town_name' => 'جالود'],
            ['city_id' => 10, 'town_name' => 'جماعين'],
            ['city_id' => 10, 'town_name' => 'جوريش'],
            ['city_id' => 10, 'town_name' => 'حوارة'],
            ['city_id' => 10, 'town_name' => 'دوما'],
            ['city_id' => 10, 'town_name' => 'دير الحطب'],
            ['city_id' => 10, 'town_name' => 'دير شرف'],
            ['city_id' => 10, 'town_name' => 'روجيب'],
            ['city_id' => 10, 'town_name' => 'زواتا'],
            ['city_id' => 10, 'town_name' => 'زيتا جماعين'],
            ['city_id' => 10, 'town_name' => 'سالم'],
            ['city_id' => 10, 'town_name' => 'سبسطية'],
            ['city_id' => 10, 'town_name' => 'صرة'],
            ['city_id' => 10, 'town_name' => 'طلوزة'],
            ['city_id' => 10, 'town_name' => 'عراق بورين'],
            ['city_id' => 10, 'town_name' => 'عزموط'],
            ['city_id' => 10, 'town_name' => 'عصيرة الشمالية'],
            ['city_id' => 10, 'town_name' => 'عصيرة القبلية'],
            ['city_id' => 10, 'town_name' => 'عقربا'],
            ['city_id' => 10, 'town_name' => 'عمورية'],
            ['city_id' => 10, 'town_name' => 'عورتا'],
            ['city_id' => 10, 'town_name' => 'عوريف'],
            ['city_id' => 10, 'town_name' => 'عين شبلي'],
            ['city_id' => 10, 'town_name' => 'عينبوس'],
            ['city_id' => 10, 'town_name' => 'فروش بيت دجن'],
            ['city_id' => 10, 'town_name' => 'قبلان'],
            ['city_id' => 10, 'town_name' => 'قريوت'],
            ['city_id' => 10, 'town_name' => 'قصرة'],
            ['city_id' => 10, 'town_name' => 'قوصين'],
            ['city_id' => 10, 'town_name' => 'كفر قليل'],
            ['city_id' => 10, 'town_name' => 'مادما'],
            ['city_id' => 10, 'town_name' => 'مجدل بني فاضل'],
            ['city_id' => 10, 'town_name' => 'مخيم بلاطة'],
            ['city_id' => 10, 'town_name' => 'مخيم عسكر'],
            ['city_id' => 10, 'town_name' => 'مخيم عين بيت الماء'],
            ['city_id' => 10, 'town_name' => 'نابلس'],
            ['city_id' => 10, 'town_name' => 'نصف جبيل'],
            ['city_id' => 10, 'town_name' => 'ياصيد'],
            ['city_id' => 10, 'town_name' => 'يانون'],
            ['city_id' => 10, 'town_name' => 'يتما'],

            //رام الله
            ['city_id' => 4, 'town_name' => 'أبو قش'],
            ['city_id' => 4, 'town_name' => 'الاتحاد'],
            ['city_id' => 4, 'town_name' => 'البيرة'],
            ['city_id' => 4, 'town_name' => 'الجانية'],
            ['city_id' => 4, 'town_name' => 'الزيتونة'],
            ['city_id' => 4, 'town_name' => 'الطيبة'],
            ['city_id' => 4, 'town_name' => 'الطيرة'],
            ['city_id' => 4, 'town_name' => 'اللبن الغربي'],
            ['city_id' => 4, 'town_name' => 'المدية'],
            ['city_id' => 4, 'town_name' => 'المزرعة الشرقية'],
            ['city_id' => 4, 'town_name' => 'المغير'],
            ['city_id' => 4, 'town_name' => 'النبي صالح'],
            ['city_id' => 4, 'town_name' => 'أم صفا'],
            ['city_id' => 4, 'town_name' => 'بدرس'],
            ['city_id' => 4, 'town_name' => 'بدو المعرجات'],
            ['city_id' => 4, 'town_name' => 'برقة'],
            ['city_id' => 4, 'town_name' => 'برهام'],
            ['city_id' => 4, 'town_name' => 'بلعين'],
            ['city_id' => 4, 'town_name' => 'بني زيد'],
            ['city_id' => 4, 'town_name' => 'بني زيد الشرقية'],
            ['city_id' => 4, 'town_name' => 'بيت سيرا'],
            ['city_id' => 4, 'town_name' => 'بيت عور التحتا'],
            ['city_id' => 4, 'town_name' => 'بيت عور الفوقا'],
            ['city_id' => 4, 'town_name' => 'بيت لقيا'],
            ['city_id' => 4, 'town_name' => 'بيت نوبا'],
            ['city_id' => 4, 'town_name' => 'بيتونيا'],
            ['city_id' => 4, 'town_name' => 'بيتين'],
            ['city_id' => 4, 'town_name' => 'بير زيت'],
            ['city_id' => 4, 'town_name' => 'ترمسعيا'],
            ['city_id' => 4, 'town_name' => 'جفنا'],
            ['city_id' => 4, 'town_name' => 'جلجيليا'],
            ['city_id' => 4, 'town_name' => 'جيبيا'],
            ['city_id' => 4, 'town_name' => 'خربة أبو فلاح'],
            ['city_id' => 4, 'town_name' => 'خربثا المصباح'],
            ['city_id' => 4, 'town_name' => 'خربثا بني حارث'],
            ['city_id' => 4, 'town_name' => 'دورا القرع'],
            ['city_id' => 4, 'town_name' => 'دير السودان'],
            ['city_id' => 4, 'town_name' => 'دير إبزيع'],
            ['city_id' => 4, 'town_name' => 'دير أبو مشعل'],
            ['city_id' => 4, 'town_name' => 'دير جرير'],
            ['city_id' => 4, 'town_name' => 'دير دبوان'],
            ['city_id' => 4, 'town_name' => 'دير قديس'],
            ['city_id' => 4, 'town_name' => 'دير نظام'],
            ['city_id' => 4, 'town_name' => 'راس كركر'],
            ['city_id' => 4, 'town_name' => 'رام الله'],
            ['city_id' => 4, 'town_name' => 'رمون'],
            ['city_id' => 4, 'town_name' => 'رنتيس'],
            ['city_id' => 4, 'town_name' => 'سلواد'],
            ['city_id' => 4, 'town_name' => 'سنجل'],
            ['city_id' => 4, 'town_name' => 'شبتين'],
            ['city_id' => 4, 'town_name' => 'شقبا'],
            ['city_id' => 4, 'town_name' => 'صردا'],
            ['city_id' => 4, 'town_name' => 'صفا'],
            ['city_id' => 4, 'town_name' => 'عابود'],
            ['city_id' => 4, 'town_name' => 'عبوين'],
            ['city_id' => 4, 'town_name' => 'عجول'],
            ['city_id' => 4, 'town_name' => 'عطارة'],
            ['city_id' => 4, 'town_name' => 'عين سينيا'],
            ['city_id' => 4, 'town_name' => 'عين عريك'],
            ['city_id' => 4, 'town_name' => 'عين قينيا'],
            ['city_id' => 4, 'town_name' => 'عين يبرود'],
            ['city_id' => 4, 'town_name' => 'قبيه'],
            ['city_id' => 4, 'town_name' => 'قراوة بني زيد'],
            ['city_id' => 4, 'town_name' => 'كفر عين'],
            ['city_id' => 4, 'town_name' => 'كفر مالك'],
            ['city_id' => 4, 'town_name' => 'كفر نعمة'],
            ['city_id' => 4, 'town_name' => 'كوبر'],
            ['city_id' => 4, 'town_name' => 'مخيم الأمعري'],
            ['city_id' => 4, 'town_name' => 'مخيم الجلزون'],
            ['city_id' => 4, 'town_name' => 'مخيم دير عمار'],
            ['city_id' => 4, 'town_name' => 'مخيم سلواد'],
            ['city_id' => 4, 'town_name' => 'مخيم قدورة'],
            ['city_id' => 4, 'town_name' => 'نعلين'],
            ['city_id' => 4, 'town_name' => 'يبرود'],

            //جنين
            ['city_id' => 8, 'town_name' => 'الجديدة'],
            ['city_id' => 8, 'town_name' => 'الجلمة'],
            ['city_id' => 8, 'town_name' => 'الخلجان'],
            ['city_id' => 8, 'town_name' => 'الرامة'],
            ['city_id' => 8, 'town_name' => 'الزاوية'],
            ['city_id' => 8, 'town_name' => 'الزبابدة'],
            ['city_id' => 8, 'town_name' => 'الشهداء'],
            ['city_id' => 8, 'town_name' => 'الطرم'],
            ['city_id' => 8, 'town_name' => 'الطيبة'],
            ['city_id' => 8, 'town_name' => 'العرقة'],
            ['city_id' => 8, 'town_name' => 'العصاعصة'],
            ['city_id' => 8, 'town_name' => 'العطارة'],
            ['city_id' => 8, 'town_name' => 'الفندقومية'],
            ['city_id' => 8, 'town_name' => 'المطلة'],
            ['city_id' => 8, 'town_name' => 'المغير'],
            ['city_id' => 8, 'town_name' => 'المنصورة'],
            ['city_id' => 8, 'town_name' => 'الهاشمية'],
            ['city_id' => 8, 'town_name' => 'اليامون'],
            ['city_id' => 8, 'town_name' => 'إمريحة'],
            ['city_id' => 8, 'town_name' => 'أم التوت'],
            ['city_id' => 8, 'town_name' => 'أم الريحان'],
            ['city_id' => 8, 'town_name' => 'أم دار'],
            ['city_id' => 8, 'town_name' => 'برطعة الشرقية'],
            ['city_id' => 8, 'town_name' => 'برقين'],
            ['city_id' => 8, 'town_name' => 'بيت قاد'],
            ['city_id' => 8, 'town_name' => 'بير الباشا'],
            ['city_id' => 8, 'town_name' => 'تعنك'],
            ['city_id' => 8, 'town_name' => 'تلفيت'],
            ['city_id' => 8, 'town_name' => 'جبع'],
            ['city_id' => 8, 'town_name' => 'جلبون'],
            ['city_id' => 8, 'town_name' => 'جلقموس'],
            ['city_id' => 8, 'town_name' => 'جنين'],
            ['city_id' => 8, 'town_name' => 'خربة عبد الله اليونس'],
            ['city_id' => 8, 'town_name' => 'دير ابو ضعيف'],
            ['city_id' => 8, 'town_name' => 'دير غزالة'],
            ['city_id' => 8, 'town_name' => 'رابا'],
            ['city_id' => 8, 'town_name' => 'رمانة'],
            ['city_id' => 8, 'town_name' => 'زبدة'],
            ['city_id' => 8, 'town_name' => 'زبوبه'],
            ['city_id' => 8, 'town_name' => 'سيريس'],
            ['city_id' => 8, 'town_name' => 'سيلة الحارثية'],
            ['city_id' => 8, 'town_name' => 'سيلة الظهر'],
            ['city_id' => 8, 'town_name' => 'صانور'],
            ['city_id' => 8, 'town_name' => 'صير'],
            ['city_id' => 8, 'town_name' => 'طورة الشرقية'],
            ['city_id' => 8, 'town_name' => 'طورة الغربية'],
            ['city_id' => 8, 'town_name' => 'ظهر العبد'],
            ['city_id' => 8, 'town_name' => 'ظهر المالح'],
            ['city_id' => 8, 'town_name' => 'عابا'],
            ['city_id' => 8, 'town_name' => 'عانين'],
            ['city_id' => 8, 'town_name' => 'عجة'],
            ['city_id' => 8, 'town_name' => 'عرابة'],
            ['city_id' => 8, 'town_name' => 'عرانة'],
            ['city_id' => 8, 'town_name' => 'عربونة'],
            ['city_id' => 8, 'town_name' => 'عنزة'],
            ['city_id' => 8, 'town_name' => 'فحمة'],
            ['city_id' => 8, 'town_name' => 'فحمة الجديدة'],
            ['city_id' => 8, 'town_name' => 'فقوعة'],
            ['city_id' => 8, 'town_name' => 'قباطية'],
            ['city_id' => 8, 'town_name' => 'كفر دان'],
            ['city_id' => 8, 'town_name' => 'كفر راعي'],
            ['city_id' => 8, 'town_name' => 'كفر قود'],
            ['city_id' => 8, 'town_name' => 'كفيرت'],
            ['city_id' => 8, 'town_name' => 'مخيم جنين'],
            ['city_id' => 8, 'town_name' => 'مركة'],
            ['city_id' => 8, 'town_name' => 'مسلية'],
            ['city_id' => 8, 'town_name' => 'ميثلون'],
            ['city_id' => 8, 'town_name' => 'نزلة الشيخ زيد'],
            ['city_id' => 8, 'town_name' => 'وادي الضبع'],
            ['city_id' => 8, 'town_name' => 'وادي دعوق'],
            ['city_id' => 8, 'town_name' => 'يعبد'],

            //بيت لحم
            ['city_id' => 15, 'town_name' => 'الجبعة'],
            ['city_id' => 15, 'town_name' => 'الحدادية'],
            ['city_id' => 15, 'town_name' => 'الخاص'],
            ['city_id' => 15, 'town_name' => 'الخضر'],
            ['city_id' => 15, 'town_name' => 'الدوحة'],
            ['city_id' => 15, 'town_name' => 'الشواورة'],
            ['city_id' => 15, 'town_name' => 'العبيدية'],
            ['city_id' => 15, 'town_name' => 'المعصرة'],
            ['city_id' => 15, 'town_name' => 'المنشية'],
            ['city_id' => 15, 'town_name' => 'المنية'],
            ['city_id' => 15, 'town_name' => 'الولجة'],
            ['city_id' => 15, 'town_name' => 'إرطاس'],
            ['city_id' => 15, 'town_name' => 'أم سلمونة'],
            ['city_id' => 15, 'town_name' => 'بتير'],
            ['city_id' => 15, 'town_name' => 'بيت تعمر'],
            ['city_id' => 15, 'town_name' => 'بيت جالا'],
            ['city_id' => 15, 'town_name' => 'بيت ساحور'],
            ['city_id' => 15, 'town_name' => 'بيت فجار'],
            ['city_id' => 15, 'town_name' => 'بيت لحم'],
            ['city_id' => 15, 'town_name' => 'بئر عونه'],
            ['city_id' => 15, 'town_name' => 'تقوع'],
            ['city_id' => 15, 'town_name' => 'جبة الذيب'],
            ['city_id' => 15, 'town_name' => 'جناتة (بيت فلوح)'],
            ['city_id' => 15, 'town_name' => 'جورة الشمعة'],
            ['city_id' => 15, 'town_name' => 'حوسان'],
            ['city_id' => 15, 'town_name' => 'خلة الحداد'],
            ['city_id' => 15, 'town_name' => 'خلة اللوزة'],
            ['city_id' => 15, 'town_name' => 'خلة النعمان'],
            ['city_id' => 15, 'town_name' => 'خلة حمامة'],
            ['city_id' => 15, 'town_name' => 'خلة سكاريا'],
            ['city_id' => 15, 'town_name' => 'دار صلاح'],
            ['city_id' => 15, 'town_name' => 'زعترة'],
            ['city_id' => 15, 'town_name' => 'عرب الرشايدة'],
            ['city_id' => 15, 'town_name' => 'كيسان'],
            ['city_id' => 15, 'town_name' => 'مخيم الدهيشة'],
            ['city_id' => 15, 'town_name' => 'مخيم العزة'],
            ['city_id' => 15, 'town_name' => 'مخيم عايدة'],
            ['city_id' => 15, 'town_name' => 'مراح رباح'],
            ['city_id' => 15, 'town_name' => 'مراح معلا'],
            ['city_id' => 15, 'town_name' => 'نحالين'],
            ['city_id' => 15, 'town_name' => 'هندازة'],
            ['city_id' => 15, 'town_name' => 'وادي النيص'],
            ['city_id' => 15, 'town_name' => 'وادي رحال'],
            ['city_id' => 15, 'town_name' => 'وادي فوكين'],

            //طولكرم
            ['city_id' => 2, 'town_name' => 'الجاروشية'],
            ['city_id' => 2, 'town_name' => 'الحفاصي'],
            ['city_id' => 2, 'town_name' => 'الراس'],
            ['city_id' => 2, 'town_name' => 'المسقوفة'],
            ['city_id' => 2, 'town_name' => 'النزلة الشرقية'],
            ['city_id' => 2, 'town_name' => 'النزلة الغربية'],
            ['city_id' => 2, 'town_name' => 'النزلة الوسطى'],
            ['city_id' => 2, 'town_name' => 'إكتابا'],
            ['city_id' => 2, 'town_name' => 'باقة الشرقية'],
            ['city_id' => 2, 'town_name' => 'بلعا'],
            ['city_id' => 2, 'town_name' => 'بيت ليد'],
            ['city_id' => 2, 'town_name' => 'خربة جبارة'],
            ['city_id' => 2, 'town_name' => 'دير الغصون'],
            ['city_id' => 2, 'town_name' => 'رامين'],
            ['city_id' => 2, 'town_name' => 'زيتا'],
            ['city_id' => 2, 'town_name' => 'سفارين'],
            ['city_id' => 2, 'town_name' => 'شوفة'],
            ['city_id' => 2, 'town_name' => 'صيدا'],
            ['city_id' => 2, 'town_name' => 'طولكرم'],
            ['city_id' => 2, 'town_name' => 'عتيل'],
            ['city_id' => 2, 'town_name' => 'عكابة'],
            ['city_id' => 2, 'town_name' => 'علار'],
            ['city_id' => 2, 'town_name' => 'عنبتا'],
            ['city_id' => 2, 'town_name' => 'فرعون'],
            ['city_id' => 2, 'town_name' => 'قفين'],
            ['city_id' => 2, 'town_name' => 'كفا'],
            ['city_id' => 2, 'town_name' => 'كفر اللبد'],
            ['city_id' => 2, 'town_name' => 'كفر جمال'],
            ['city_id' => 2, 'town_name' => 'كفر زيباد'],
            ['city_id' => 2, 'town_name' => 'كفر صور'],
            ['city_id' => 2, 'town_name' => 'كفر عبوش'],
            ['city_id' => 2, 'town_name' => 'كور'],
            ['city_id' => 2, 'town_name' => 'مخيم طولكرم'],
            ['city_id' => 2, 'town_name' => 'مخيم نور شمس'],
            ['city_id' => 2, 'town_name' => 'نزلة عيسى'],

            //قلقيلية
            ['city_id' => 5, 'town_name' => 'الضبعة'],
            ['city_id' => 5, 'town_name' => 'الفندق'],
            ['city_id' => 5, 'town_name' => 'المدور'],
            ['city_id' => 5, 'town_name' => 'النبي إلياس'],
            ['city_id' => 5, 'town_name' => 'إماتين'],
            ['city_id' => 5, 'town_name' => 'باقة الحطب'],
            ['city_id' => 5, 'town_name' => 'بيت أمين'],
            ['city_id' => 5, 'town_name' => 'جنصافوط'],
            ['city_id' => 5, 'town_name' => 'جيت'],
            ['city_id' => 5, 'town_name' => 'جيوس'],
            ['city_id' => 5, 'town_name' => 'حبلة'],
            ['city_id' => 5, 'town_name' => 'حجة'],
            ['city_id' => 5, 'town_name' => 'خربة صير'],
            ['city_id' => 5, 'town_name' => 'راس الطيرة'],
            ['city_id' => 5, 'town_name' => 'راس عطية'],
            ['city_id' => 5, 'town_name' => 'سنيريا'],
            ['city_id' => 5, 'town_name' => 'عرب الرماضين الجنوبي'],
            ['city_id' => 5, 'town_name' => 'عرب أبو فردة'],
            ['city_id' => 5, 'town_name' => 'عزبة الأشقر'],
            ['city_id' => 5, 'town_name' => 'عزبة الطبيب'],
            ['city_id' => 5, 'town_name' => 'عزبة جلعود'],
            ['city_id' => 5, 'town_name' => 'عزبة سلمان'],
            ['city_id' => 5, 'town_name' => 'عزون'],
            ['city_id' => 5, 'town_name' => 'عسلة'],
            ['city_id' => 5, 'town_name' => 'فرعتا'],
            ['city_id' => 5, 'town_name' => 'فلامية'],
            ['city_id' => 5, 'town_name' => 'قلقيلية'],
            ['city_id' => 5, 'town_name' => 'كفر ثلث'],
            ['city_id' => 5, 'town_name' => 'كفر قدوم'],
            ['city_id' => 5, 'town_name' => 'كفر لاقف'],
            ['city_id' => 5, 'town_name' => 'وادي الرشا'],

            //القدس
            ['city_id' => 9, 'town_name' => 'أبو ديس'],
            ['city_id' => 9, 'town_name' => 'الجديرة'],
            ['city_id' => 9, 'town_name' => 'الجيب'],
            ['city_id' => 9, 'town_name' => 'الرام وضاحية البريد'],
            ['city_id' => 9, 'town_name' => 'الزعيم'],
            ['city_id' => 9, 'town_name' => 'السواحرة الشرقية'],
            ['city_id' => 9, 'town_name' => 'الشيخ سعد'],
            ['city_id' => 9, 'town_name' => 'العيزرية'],
            ['city_id' => 9, 'town_name' => 'القبيبة'],
            ['city_id' => 9, 'town_name' => 'الكعابنه (تجمع بدوي)'],
            ['city_id' => 9, 'town_name' => 'النبي صموئيل'],
            ['city_id' => 9, 'town_name' => 'بدو'],
            ['city_id' => 9, 'town_name' => 'بيت إجزا'],
            ['city_id' => 9, 'town_name' => 'بيت إكسا'],
            ['city_id' => 9, 'town_name' => 'بيت حنينا البلد'],
            ['city_id' => 9, 'town_name' => 'بيت دقو'],
            ['city_id' => 9, 'town_name' => 'بيت سوريك'],
            ['city_id' => 9, 'town_name' => 'بيت عنان'],
            ['city_id' => 9, 'town_name' => 'بير نبالا'],
            ['city_id' => 9, 'town_name' => 'جبع'],
            ['city_id' => 9, 'town_name' => 'حزما'],
            ['city_id' => 9, 'town_name' => 'خرائب أم اللحم'],
            ['city_id' => 9, 'town_name' => 'رافات'],
            ['city_id' => 9, 'town_name' => 'عرب الجهالين'],
            ['city_id' => 9, 'town_name' => 'عناتا'],
            ['city_id' => 9, 'town_name' => 'قطنه'],
            ['city_id' => 9, 'town_name' => 'قلنديا'],
            ['city_id' => 9, 'town_name' => 'مخماس'],
            ['city_id' => 9, 'town_name' => 'مخيم قلنديا'],

            //سلفيت
            ['city_id' => 16, 'town_name' => 'الزاوية'],
            ['city_id' => 16, 'town_name' => 'إسكاكا'],
            ['city_id' => 16, 'town_name' => 'بديا'],
            ['city_id' => 16, 'town_name' => 'بروقين'],
            ['city_id' => 16, 'town_name' => 'حارس'],
            ['city_id' => 16, 'town_name' => 'خربة قيس'],
            ['city_id' => 16, 'town_name' => 'دير إستيا'],
            ['city_id' => 16, 'town_name' => 'دير بلوط'],
            ['city_id' => 16, 'town_name' => 'رافات'],
            ['city_id' => 16, 'town_name' => 'سلفيت'],
            ['city_id' => 16, 'town_name' => 'صرطة'],
            ['city_id' => 16, 'town_name' => 'فرخة'],
            ['city_id' => 16, 'town_name' => 'قراوة بني حسان'],
            ['city_id' => 16, 'town_name' => 'قيرة'],
            ['city_id' => 16, 'town_name' => 'كفر الديك'],
            ['city_id' => 16, 'town_name' => 'كفل حارس'],
            ['city_id' => 16, 'town_name' => 'مردا'],
            ['city_id' => 16, 'town_name' => 'مسحة'],
            ['city_id' => 16, 'town_name' => 'ياسوف'],

            //طوباس
            ['city_id' => 14, 'town_name' => 'المالح'],
            ['city_id' => 14, 'town_name' => 'الثغرة'],
            ['city_id' => 14, 'town_name' => 'العقبة'],
            ['city_id' => 14, 'town_name' => 'الفارسية'],
            ['city_id' => 14, 'town_name' => 'إبزيق'],
            ['city_id' => 14, 'town_name' => 'بردلة'],
            ['city_id' => 14, 'town_name' => 'تياسير'],
            ['city_id' => 14, 'town_name' => 'خربة الراس الأحمر'],
            ['city_id' => 14, 'town_name' => 'خربة حمصة'],
            ['city_id' => 14, 'town_name' => 'خربة عاطوف'],
            ['city_id' => 14, 'town_name' => 'راس الفارعة'],
            ['city_id' => 14, 'town_name' => 'طمون'],
            ['city_id' => 14, 'town_name' => 'طوباس'],
            ['city_id' => 14, 'town_name' => 'عقابه'],
            ['city_id' => 14, 'town_name' => 'عين البيضا'],
            ['city_id' => 14, 'town_name' => 'كردلة'],
            ['city_id' => 14, 'town_name' => 'مخيم الفارعة'],
            ['city_id' => 14, 'town_name' => 'وادي الفارعة'],

            //اريحا
            ['city_id' => 6, 'town_name' => 'الجفتلك'],
            ['city_id' => 6, 'town_name' => 'الزبيدات'],
            ['city_id' => 6, 'town_name' => 'العوجا'],
            ['city_id' => 6, 'town_name' => 'النبي موسى'],
            ['city_id' => 6, 'town_name' => 'النويعمة'],
            ['city_id' => 6, 'town_name' => 'أريحا'],
            ['city_id' => 6, 'town_name' => 'عين الديوك الفوقا'],
            ['city_id' => 6, 'town_name' => 'فصايل'],
            ['city_id' => 6, 'town_name' => 'مخيم عقبة جبر'],
            ['city_id' => 6, 'town_name' => 'مخيم عين السلطان'],
            ['city_id' => 6, 'town_name' => 'مرج الغزال'],
            ['city_id' => 6, 'town_name' => 'مرج نعجة'],

            //شمال غزة
            ['city_id' => 18, 'town_name' => 'مخيم جباليا'],
            ['city_id' => 18, 'town_name' => 'جباليا'],
            ['city_id' => 18, 'town_name' => 'بيت لاهيا'],
            ['city_id' => 18, 'town_name' => 'بيت حانون'],
            ['city_id' => 18, 'town_name' => 'أم النصر (القرية البدوية)'],

            //غزة
            ['city_id' => 7, 'town_name' => 'مدينة الزهراء'],
            ['city_id' => 7, 'town_name' => 'مخيم الشاطىء'],
            ['city_id' => 7, 'town_name' => 'غزة'],
            ['city_id' => 7, 'town_name' => 'جحر الديك'],
            ['city_id' => 7, 'town_name' => 'المغراقه'],

            //خانيونس
            ['city_id' => 12, 'town_name' => 'عبسان الكبيرة'],
            ['city_id' => 12, 'town_name' => 'عبسان الجديدة'],
            ['city_id' => 12, 'town_name' => 'خزاعة'],
            ['city_id' => 12, 'town_name' => 'مخيم خانيونس'],
            ['city_id' => 12, 'town_name' => 'خانيونس'],
            ['city_id' => 12, 'town_name' => 'بني سهيلا'],
            ['city_id' => 12, 'town_name' => 'القرارة'],
            ['city_id' => 12, 'town_name' => 'الفخاري'],

            //دير البلح
            ['city_id' => 17, 'town_name' => 'وادي السلقا'],
            ['city_id' => 17, 'town_name' => 'مخيم دير البلح'],
            ['city_id' => 17, 'town_name' => 'دير البلح'],
            ['city_id' => 17, 'town_name' => 'مخيم النصيرات'],
            ['city_id' => 17, 'town_name' => 'النصيرات'],
            ['city_id' => 17, 'town_name' => 'مخيم المغازي'],
            ['city_id' => 17, 'town_name' => 'المغازي'],
            ['city_id' => 17, 'town_name' => 'المصدر'],
            ['city_id' => 17, 'town_name' => 'الزوايدة'],
            ['city_id' => 17, 'town_name' => 'مخيم البريج'],
            ['city_id' => 17, 'town_name' => 'البريج'],

            //رفح
            ['city_id' => 13, 'town_name' => 'مخيم رفح'],
            ['city_id' => 13, 'town_name' => 'رفح'],
            ['city_id' => 13, 'town_name' => 'النصر'],
            ['city_id' => 13, 'town_name' => 'الشوكة'],
        ];

        DB::table('towns')->insert($towns);
    }
}
